/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banca.en.línea.SplashScreen;
import banca.en.línea.registro2;
import banca.en.línea.login1;

import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Edgardo
 */
public class Bienvenido extends javax.swing.JFrame {
    public Bienvenido() {
        initComponents();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        BackgroundImage = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Cargando = new javax.swing.JLabel();
        LoadingValue = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackGroundPanel = new javax.swing.JPanel();
        LoadingBar = new javax.swing.JProgressBar();

        BackgroundImage.setBackground(new java.awt.Color(26, 29, 83));
        BackgroundImage.setForeground(new java.awt.Color(26, 29, 83));
        BackgroundImage.setText("jLabel1");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banca/en/línea/SplashScreen/bienvenido_reducido.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Cargando.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Cargando.setForeground(new java.awt.Color(255, 255, 255));
        Cargando.setText("Cargando...");
        getContentPane().add(Cargando, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        LoadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        LoadingValue.setForeground(new java.awt.Color(255, 255, 255));
        LoadingValue.setText("0 %");
        getContentPane().add(LoadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 490, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(37, 201, 152));
        jButton1.setText("Iniciar");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 400, 170, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/banca/en/línea/SplashScreen/bienvenido_reducido.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 960, 520));

        BackGroundPanel.setBackground(new java.awt.Color(26, 29, 83));
        BackGroundPanel.setPreferredSize(new java.awt.Dimension(900, 500));
        BackGroundPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        BackGroundPanel.add(LoadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 940, 20));

        getContentPane().add(BackGroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 11, 940, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        login1 reg = new login1();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */ 
  
          
   
   
     
      
    public static void main(String args[]) { 
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        
                try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bienvenido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                                       
      
        
        
        Bienvenido bi = new Bienvenido();
        bi.setVisible(true);
         
        
        try{
            for (int i=0; i<100; i++){
                Thread.sleep(100);
                bi.LoadingValue.setText(i +"%");
                
                if(i==10){
                    bi.Cargando.setText("Conectando los modulos...");
                }
                
                if(i==30){
                    bi.Cargando.setText("Cargando los modulos...");
                }
                
                if(i==50){
                    bi.Cargando.setText("Conectando a la base de datos...");
                }
                
                if(i==70){
                    bi.Cargando.setText("Base de datos conectada...");
                    
                }
                
                if(i==80){
                    bi.Cargando.setText("Iniciando aplicación...");
                }
                bi.LoadingBar.setValue(i);
            }
        } catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackGroundPanel;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel Cargando;
    private javax.swing.JProgressBar LoadingBar;
    private javax.swing.JLabel LoadingValue;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}

