/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banca.en.línea;

import banca.en.línea.index;
import banca.en.línea.login1;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Edgardo
 */
public class Consultar extends javax.swing.JFrame {

    public static String numcuenta = "";
    /**
     * Creates new form Consultar
     */
    public Consultar() {
        initComponents();
        txtRecibir.setText(login1.texto);
        txtRecibir.setVisible(false); 
        txtNumeroDeCuenta.setEditable(false);
        txtTipoDeCuenta.setEditable(false);
        txtNombre.setEditable(false);
        txtSaldo.setEditable(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtTipoDeCuenta = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumeroDeCuenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        verdecito_panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSaldo = new javax.swing.JTextField();
        azul_panel = new javax.swing.JPanel();
        btnAtras = new javax.swing.JButton();
        btnDatos = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        labelPrueba = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtRecibir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTipoDeCuenta.setBackground(new java.awt.Color(26, 29, 83));
        txtTipoDeCuenta.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtTipoDeCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtTipoDeCuenta.setAutoscrolls(false);
        txtTipoDeCuenta.setBorder(null);
        txtTipoDeCuenta.setOpaque(false);
        txtTipoDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoDeCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtTipoDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 210, 40));

        txtNombre.setBackground(new java.awt.Color(26, 29, 83));
        txtNombre.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(null);
        txtNombre.setOpaque(false);
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 210, 30));

        txtNumeroDeCuenta.setBackground(new java.awt.Color(26, 29, 83));
        txtNumeroDeCuenta.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        txtNumeroDeCuenta.setForeground(new java.awt.Color(255, 255, 255));
        txtNumeroDeCuenta.setBorder(null);
        txtNumeroDeCuenta.setOpaque(false);
        txtNumeroDeCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroDeCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroDeCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 210, 40));

        jLabel2.setBackground(new java.awt.Color(217, 217, 217));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(26, 29, 83));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Información Cuenta");
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 320, 20));

        verdecito_panel.setBackground(new java.awt.Color(37, 201, 152));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(26, 29, 83));
        jLabel1.setText("Saldo Actual");

        txtSaldo.setBackground(new java.awt.Color(37, 201, 152));
        txtSaldo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        txtSaldo.setForeground(new java.awt.Color(26, 29, 83));
        txtSaldo.setHorizontalAlignment(javax.swing.JTextField.TRAILING);
        txtSaldo.setBorder(null);
        txtSaldo.setOpaque(false);
        txtSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSaldoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout verdecito_panelLayout = new javax.swing.GroupLayout(verdecito_panel);
        verdecito_panel.setLayout(verdecito_panelLayout);
        verdecito_panelLayout.setHorizontalGroup(
            verdecito_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verdecito_panelLayout.createSequentialGroup()
                .addGroup(verdecito_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        verdecito_panelLayout.setVerticalGroup(
            verdecito_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(verdecito_panelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(verdecito_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 160, 70));

        azul_panel.setBackground(new java.awt.Color(26, 29, 83));

        btnAtras.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtras.setForeground(new java.awt.Color(26, 29, 83));
        btnAtras.setText("Atras");
        btnAtras.setBorderPainted(false);
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        btnDatos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDatos.setForeground(new java.awt.Color(26, 29, 83));
        btnDatos.setText("Rellenar Datos");
        btnDatos.setBorderPainted(false);
        btnDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatosActionPerformed(evt);
            }
        });

        btnCerrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(26, 29, 83));
        btnCerrar.setText("Cerrar sesión");
        btnCerrar.setBorderPainted(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnTransferencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTransferencia.setForeground(new java.awt.Color(26, 29, 83));
        btnTransferencia.setText("Transferencia");
        btnTransferencia.setBorderPainted(false);
        btnTransferencia.setSelected(true);
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout azul_panelLayout = new javax.swing.GroupLayout(azul_panel);
        azul_panel.setLayout(azul_panelLayout);
        azul_panelLayout.setHorizontalGroup(
            azul_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(azul_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(azul_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(azul_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransferencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        azul_panelLayout.setVerticalGroup(
            azul_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, azul_panelLayout.createSequentialGroup()
                .addGroup(azul_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(azul_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(azul_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, 100));
        getContentPane().add(labelPrueba, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 62, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bienvenido_arch/consulta_plantilla.png"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -20, 340, 450));
        getContentPane().add(txtRecibir, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 110, 51, 17));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroDeCuentaActionPerformed
            
    }//GEN-LAST:event_txtNumeroDeCuentaActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtTipoDeCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTipoDeCuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTipoDeCuentaActionPerformed

    private void txtSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSaldoActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        index reg = new index();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        login1 reg = new login1();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatosActionPerformed
        Conexion obj = new Conexion();
         Connection conex = obj.Conectarse();
        try{
            String sql = "Select * from registro where usuario="+txtRecibir.getText();
            PreparedStatement pst = conex.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();     
            if(rs.next()){
               txtNumeroDeCuenta.setText(rs.getString("num_cuenta"));
               txtTipoDeCuenta.setText(rs.getString("tipo_cuenta"));
               txtNombre.setText(rs.getString("nombre"));
               txtSaldo.setText(rs.getString("monto"));
               numcuenta = txtNumeroDeCuenta.getText();
            }
            else{
                JOptionPane.showMessageDialog(null, "no sirve");
            }
            conex.close();
            pst.close();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_btnDatosActionPerformed

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
        Transferenciadv reg = new Transferenciadv();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnTransferenciaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel azul_panel;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnDatos;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel labelPrueba;
    public static javax.swing.JTextField txtNombre;
    public static javax.swing.JTextField txtNumeroDeCuenta;
    public static javax.swing.JLabel txtRecibir;
    public static javax.swing.JTextField txtSaldo;
    public static javax.swing.JTextField txtTipoDeCuenta;
    private javax.swing.JPanel verdecito_panel;
    // End of variables declaration//GEN-END:variables
}
