/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banca.en.línea;

import javax.swing.JFrame;

/**
 *
 * @author Edgardo
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gris_label = new javax.swing.JLabel();
        btnTransferencia = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        Cerrar_label = new javax.swing.JLabel();
        SESION_label1 = new javax.swing.JLabel();
        TRANSFERENCIA_label = new javax.swing.JLabel();
        Bancaria_Label = new javax.swing.JLabel();
        Bienvenido_Label = new javax.swing.JLabel();
        Consulta_label = new javax.swing.JLabel();
        Cuenta_Label = new javax.swing.JLabel();
        fondo_label = new javax.swing.JLabel();
        azul_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gris_label.setBackground(new java.awt.Color(217, 217, 217));
        gris_label.setOpaque(true);
        getContentPane().add(gris_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 10, 70));

        btnTransferencia.setBorderPainted(false);
        btnTransferencia.setContentAreaFilled(false);
        btnTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, 90));

        btnConsultar.setBackground(new java.awt.Color(153, 255, 255));
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setVerifyInputWhenFocusTarget(false);
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 210, 80));

        btnCerrar.setBorderPainted(false);
        btnCerrar.setContentAreaFilled(false);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 210, 80));

        Cerrar_label.setBackground(new java.awt.Color(242, 242, 242));
        Cerrar_label.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        Cerrar_label.setForeground(new java.awt.Color(26, 29, 83));
        Cerrar_label.setText("CERRAR");
        Cerrar_label.setOpaque(true);
        getContentPane().add(Cerrar_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 80, 30));

        SESION_label1.setBackground(new java.awt.Color(242, 242, 242));
        SESION_label1.setFont(new java.awt.Font("Arial Black", 1, 16)); // NOI18N
        SESION_label1.setForeground(new java.awt.Color(26, 29, 83));
        SESION_label1.setText("SESIÓN");
        SESION_label1.setOpaque(true);
        getContentPane().add(SESION_label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 350, 80, 40));

        TRANSFERENCIA_label.setBackground(new java.awt.Color(242, 242, 242));
        TRANSFERENCIA_label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        TRANSFERENCIA_label.setForeground(new java.awt.Color(26, 29, 83));
        TRANSFERENCIA_label.setText("TRANSFERENCIA");
        TRANSFERENCIA_label.setOpaque(true);
        getContentPane().add(TRANSFERENCIA_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, -1, 30));

        Bancaria_Label.setBackground(new java.awt.Color(242, 242, 242));
        Bancaria_Label.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        Bancaria_Label.setForeground(new java.awt.Color(26, 29, 83));
        Bancaria_Label.setText("BANCARIA");
        Bancaria_Label.setOpaque(true);
        getContentPane().add(Bancaria_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 90, 30));

        Bienvenido_Label.setBackground(new java.awt.Color(217, 217, 217));
        Bienvenido_Label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Bienvenido_Label.setForeground(new java.awt.Color(26, 29, 83));
        Bienvenido_Label.setText("Bienvenido");
        Bienvenido_Label.setOpaque(true);
        getContentPane().add(Bienvenido_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 180, 50));

        Consulta_label.setBackground(new java.awt.Color(242, 242, 242));
        Consulta_label.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Consulta_label.setForeground(new java.awt.Color(26, 29, 83));
        Consulta_label.setText("CONSULTAR ");
        Consulta_label.setOpaque(true);
        getContentPane().add(Consulta_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 120, 30));

        Cuenta_Label.setBackground(new java.awt.Color(242, 242, 242));
        Cuenta_Label.setFont(new java.awt.Font("Arial Black", 0, 16)); // NOI18N
        Cuenta_Label.setForeground(new java.awt.Color(26, 29, 83));
        Cuenta_Label.setText("CUENTA");
        Cuenta_Label.setOpaque(true);
        getContentPane().add(Cuenta_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, 40));

        fondo_label.setBackground(new java.awt.Color(51, 255, 255));
        fondo_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bienvenido_arch/Pre-bienvenida_Reducido.png"))); // NOI18N
        fondo_label.setOpaque(true);
        getContentPane().add(fondo_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 310, 430));

        azul_label.setBackground(new java.awt.Color(26, 29, 89));
        azul_label.setOpaque(true);
        getContentPane().add(azul_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 414, 310, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferenciaActionPerformed
        Transferenciadv reg = new Transferenciadv();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnTransferenciaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        Consultar reg = new Consultar();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        login1 reg = new login1();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bancaria_Label;
    private javax.swing.JLabel Bienvenido_Label;
    private javax.swing.JLabel Cerrar_label;
    private javax.swing.JLabel Consulta_label;
    private javax.swing.JLabel Cuenta_Label;
    private javax.swing.JLabel SESION_label1;
    private javax.swing.JLabel TRANSFERENCIA_label;
    private javax.swing.JLabel azul_label;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel fondo_label;
    private javax.swing.JLabel gris_label;
    // End of variables declaration//GEN-END:variables
}
