package banca.en.línea;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import banca.en.línea.Recepcion;
import banca.en.línea.index;
import banca.en.línea.login1;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Edgardo
 */
public class Transferenciadv extends javax.swing.JFrame {

    public static final String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    private static final String usuario = "usuarioSql";
    private static String contraseña = "321";
    private static final String url ="jdbc:sqlserver://DESKTOP-TDSIKRJ:1433; Database=registropro" ;
    String cuenta, str, fecha;
    float cant, validar_monto, descripcion, num_referencia;
    public static String numref;
    Conexion obj = new Conexion();
    /**
     * Creates new form registro2
     */
    public Transferenciadv() {
        initComponents();
        escondido.setText(login1.texto);
        escondido.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        debito = new javax.swing.JTextField();
        date = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        descrip = new javax.swing.JTextField();
        monto = new javax.swing.JTextField();
        beneficiario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        credito = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        escondido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(305, 410));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(242, 242, 242));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 153));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Cuenta Debito");
        jLabel13.setOpaque(true);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 50, 300, 20));

        jLabel12.setBackground(new java.awt.Color(242, 242, 242));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 153));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Cuenta Credito");
        jLabel12.setOpaque(true);
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 290, 20));

        jLabel5.setBackground(new java.awt.Color(37, 201, 152));
        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(26, 29, 83));
        jLabel5.setText("TRANSFERENCIA");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 210, 50));

        debito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        debito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        debito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitoActionPerformed(evt);
            }
        });
        debito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                debitoKeyReleased(evt);
            }
        });
        getContentPane().add(debito, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 150, 20));

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        date.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateActionPerformed(evt);
            }
        });
        date.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateKeyReleased(evt);
            }
        });
        getContentPane().add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 150, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText(" Beneficiario:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Monto :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Fecha :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 50, -1));

        descrip.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        descrip.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descripActionPerformed(evt);
            }
        });
        getContentPane().add(descrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 150, 20));

        monto.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        monto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoKeyTyped(evt);
            }
        });
        getContentPane().add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, 150, 20));

        beneficiario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        beneficiario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        beneficiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beneficiarioActionPerformed(evt);
            }
        });
        getContentPane().add(beneficiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 150, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Num. Cuenta :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 90, 20));

        credito.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        credito.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        credito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditoActionPerformed(evt);
            }
        });
        getContentPane().add(credito, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 150, -1));

        btnEnviar.setForeground(new java.awt.Color(26, 29, 83));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 90, -1));

        btnAtras.setForeground(new java.awt.Color(26, 29, 83));
        btnAtras.setText("Atras");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 80, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Num. Cuenta :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("Descripcion :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 20));

        jLabel3.setBackground(new java.awt.Color(26, 29, 83));
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 290, 330));

        jLabel11.setBackground(new java.awt.Color(26, 29, 83));
        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setOpaque(true);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 100, 110));

        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Bienvenido_arch/Transferencia_plantilla.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 310, 410));

        jLabel10.setBackground(new java.awt.Color(26, 29, 83));
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setOpaque(true);
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 110, 70));
        getContentPane().add(escondido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 40, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void debitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_debitoActionPerformed

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descripActionPerformed

    private void dateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateActionPerformed

    private void creditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        
        try {
            Connection conex = obj.Conectarse( );
            String sql = "select * from registro where num_cuenta=?"; // CONSULTA PARA VALIDAR QUE LA CUENTA DESTINO EXISTE
            PreparedStatement pst = conex.prepareStatement(sql);
            pst.setString(1, credito.getText( ));
            
            ResultSet rs = pst.executeQuery( );
            
            if(rs.next( )) {
                
                rs.close( ); // Se cierra la consulta anterior
                        
                sql = "select * from registro where usuario=?"; // CONSULTA PARA VALIDAR QUE EL NOMBRE DE USUARIO DESTINO EXISTE
                pst = conex.prepareStatement(sql);
                pst.setString(1, beneficiario.getText( ));
                rs = pst.executeQuery( );
                    
                   if(rs.next( )) {
                       
                       rs.close( ); // Se cierra la consulta anterior
                       
                       sql = "select monto from registro where usuario=?"; // CONSULTA PARA VALIDAR QUE EL MONTO QUE SE QUIERE TRANSFERIR ESTA DISPONIBLE
                       pst = conex.prepareStatement(sql);
                       pst.setString(1, escondido.getText());
                       rs = pst.executeQuery( );
                       cant = Float.parseFloat(monto.getText( ));
                       
                            if(rs.next( )) {
                                
                                validar_monto = rs.getFloat("monto");
                
                                    if(cant>validar_monto) {
                        
                                            JOptionPane.showMessageDialog(null, "Su saldo es: " + validar_monto + " y usted introdujo: " + 
                                            cant + " no puede realizar la transferencia.");
                                    }
                            
                                    else {
                                
                                        float cant2 = validar_monto - cant;
                                        sql = "UPDATE registro set monto=? where num_cuenta=?";
                                        pst = conex.prepareStatement(sql);
                                        pst.setString(1, Float.toString(cant2));
                                        pst.setString(2, debito.getText( ));
                                        int columnas = pst.executeUpdate( );
                                        pst.close( );
                                        //-------------------------------------------------------------
                                        
                                        sql = "select monto from registro where num_cuenta=?"; 
                                        pst = conex.prepareStatement(sql);
                                        pst.setString(1, credito.getText( ));
                                        rs = pst.executeQuery( );
                                        
                                            if(rs.next( ))
                                                validar_monto = rs.getFloat("monto");
                                        
                                        rs.close( );
                                        //-------------------------------------------------------------
                                        
                                        cant2 = validar_monto + cant;
                                        sql = "UPDATE registro set monto=? where num_cuenta=?";
                                        pst = conex.prepareStatement(sql);
                                        pst.setString(1, Float.toString(cant2));
                                        pst.setString(2, credito.getText( ));
                                        columnas = pst.executeUpdate( );
                                        pst.close( );
                                        //-------------------------------------------------------------
                                        
                                        sql = "insert INTO transferencia VALUES (?,?,?,?,?,?,?)";
                                        pst = conex.prepareStatement(sql);
                                        Random rand = new Random( );
                                        String ref = Integer.toString(rand.nextInt(100000));
                                        pst.setString(1, ref);
                                        pst.setString(2, cuenta);
                                        pst.setString(3, credito.getText( ));
                                        pst.setString(4, Float.toString(cant));
                                        pst.setString(5, descrip.getText( ));
                                        pst.setString(6, fecha);
                                        pst.setString(7, beneficiario.getText( ));
                                        pst.executeUpdate( );
                                        
                                        numref = ref;
                                        
                                        pst.close();
                                        
                                        JOptionPane.showMessageDialog(null, "Pago realizado correctamente!");
                                        Recepcion reg = new Recepcion();
                                        reg.setVisible(true);
                                        reg.pack();
                                        reg.setLocationRelativeTo(null);
                                        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                                        this.dispose();
                                        
                                    }
                            }
                            else {
                                JOptionPane.showMessageDialog(null, "Hubo un error validando el monto disponible en su cuenta.");
                            }
                   }
                   else {
                       JOptionPane.showMessageDialog(null, "Hubo un error el nombre de usuario no existe.");
                   }
                
            }
            else {
                
                JOptionPane.showMessageDialog(null, "Hubo un error la cuenta destino no existe!");
            }
            
            
        }catch (Exception e) {
            e.printStackTrace( );
        }
       
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        index reg = new index();
        reg.setVisible(true);
        reg.pack();
        reg.setLocationRelativeTo(null);
        reg.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void dateKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateKeyReleased
        Date objDate = new Date( );
        fecha = objDate.toString( );
        date.setText(fecha);
    }//GEN-LAST:event_dateKeyReleased

    private void debitoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_debitoKeyReleased
        try {
            Connection conex1 = obj.Conectarse();
            String sql = "select num_cuenta from registro where usuario="+escondido.getText();
            PreparedStatement pst = conex1.prepareStatement(sql);
            ResultSet rs = pst.executeQuery( );
            
            if(rs.next( )) {
                
                
                cuenta = rs.getString("num_cuenta");
                debito.setText(cuenta);
            }
            else {
                
                JOptionPane.showMessageDialog(null, "Ha ocurrido un error.");
            }
            
            
            rs.close( );
                    
        }catch (Exception e) {
            
            e.printStackTrace( );
        }
    }//GEN-LAST:event_debitoKeyReleased

    private void montoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyTyped
        char validar = evt.getKeyChar();
        if(Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(null, "Introduzca un número.");
        }      
    }//GEN-LAST:event_montoKeyTyped

    private void beneficiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beneficiarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_beneficiarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        String nombre, cuenta, contra;
        float monto;
        int usuario;
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferenciadv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferenciadv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferenciadv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferenciadv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferenciadv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField beneficiario;
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JTextField credito;
    private javax.swing.JTextField date;
    private javax.swing.JTextField debito;
    private javax.swing.JTextField descrip;
    private javax.swing.JLabel escondido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField monto;
    // End of variables declaration//GEN-END:variables
}
